
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Srijan Tripathi
 */
public class NewJFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form NewJFrame
     */
    
    
    //identifing the turn
    int turn = 2;
    
    //checking whether a button has been used before or not
    int buttonUsed[] = {0,0,0,0,0,0,0,0,0};
    
    
    //finding which player has won by initializing 2 arrays for both the players
    int p1won[] = {0,0,0,0,0,0,0,0,0};
    int p2won[] = {0,0,0,0,0,0,0,0,0};
    
    
    
    //function to find the whether p1 is winner
    int p1won()
    {
        if(p1won[0]==1 && p1won[1]==1 && p1won[2]==1)
        {
            return 1;
        }
        if(p1won[3]==1 && p1won[4]==1 && p1won[5]==1)
        {
            return 1;
        }
        if(p1won[6]==1 && p1won[7]==1 && p1won[8]==1)
        {
            return 1;
        }
        if(p1won[0]==1 && p1won[3]==1 && p1won[6]==1)
        {
            return 1;
        }
        if(p1won[1]==1 && p1won[4]==1 && p1won[7]==1)
        {
            return 1;
        }
        if(p1won[2]==1 && p1won[5]==1 && p1won[8]==1)
        {
            return 1;
        }
        if(p1won[0]==1 && p1won[4]==1 && p1won[8]==1)
        {
            return 1;
        }
        if(p1won[2]==1 && p1won[4]==1 && p1won[6]==1)
        {
            return 1;
        }
        return 0;
    }
    
    
    //function to find the whether p1 is winner
    int p2won()
    {
        if(p2won[0]==1 && p2won[1]==1 && p2won[2]==1)
        {
            return 1;
        }
        if(p2won[3]==1 && p2won[4]==1 && p2won[5]==1)
        {
            return 1;
        }
        if(p2won[6]==1 && p2won[7]==1 && p2won[8]==1)
        {
            return 1;
        }
        if(p2won[0]==1 && p2won[3]==1 && p2won[6]==1)
        {
            return 1;
        }
        if(p2won[1]==1 && p2won[4]==1 && p2won[7]==1)
        {
            return 1;
        }
        if(p2won[2]==1 && p2won[5]==1 && p2won[8]==1)
        {
            return 1;
        }
        if(p2won[0]==1 && p2won[4]==1 && p2won[8]==1)
        {
            return 1;
        }
        if(p2won[2]==1 && p2won[4]==1 && p2won[6]==1)
        {
            return 1;
        }
        return 0;
    }
    
    
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setResizable(false);

        b1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 0, 51));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 255));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 0, 51));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 255));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 0, 51));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 0, 255));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 0, 51));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b8.setForeground(new java.awt.Color(0, 0, 255));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 0, 51));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        resetBtn.setText("Play Again");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[0]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b1.setText("X");
                buttonUsed[0]=1;
                p1won[0]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
            else
            {
                turn++;
                b1.setText("O");
                buttonUsed[0]=1;
                p2won[0]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button Has Already Been Used !");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[1]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b2.setText("X");
                buttonUsed[1]=1;
                p1won[1]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
            else
            {
                turn++;
                b2.setText("O");
                buttonUsed[1]=1;
                p2won[1]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button Has Already Been Used !");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[2]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b3.setText("X");
                buttonUsed[2]=1;
                p1won[2]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
            else
            {
                turn++;
                b3.setText("O");
                buttonUsed[2]=1;
                p2won[2]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button Has Already Been Used !");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[3]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b4.setText("X");
                buttonUsed[3]=1;
                p1won[3]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
            else
            {
                turn++;
                b4.setText("O");
                buttonUsed[3]=1;
                p2won[3]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button Has Already Been Used !");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[4]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b5.setText("X");
                buttonUsed[4]=1;
                p1won[4]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
            else
            {
                turn++;
                b5.setText("O");
                buttonUsed[4]=1;
                p2won[4]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button Has Already Been Used !");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[5]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b6.setText("X");
                buttonUsed[5]=1;
                p1won[5]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
            else
            {
                turn++;
                b6.setText("O");
                buttonUsed[5]=1;
                p2won[5]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button Has Already Been Used !");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[6]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b7.setText("X");
                buttonUsed[6]=1;
                p1won[6]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
            else
            {
                turn++;
                b7.setText("O");
                buttonUsed[6]=1;
                p2won[6]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button Has Already Been Used !");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[7]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b8.setText("X");
                buttonUsed[7]=1;
                p1won[7]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
            else
            {
                turn++;
                b8.setText("O");
                buttonUsed[7]=1;
                p2won[7]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button Has Already Been Used !");
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[8]==0)
        {
            if(turn%2==0)
            {
                turn++;
                b9.setText("X");
                buttonUsed[8]=1;
                p1won[8]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
            else
            {
                turn++;
                b9.setText("O");
                buttonUsed[8]=1;
                p2won[8]=1;
                
                //winner checked at each button press
                int result1=p1won();
                int result2=p2won();
                
                if(result1==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 1 You Have Won***");
                }
                else if(result2==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Congratulations! Player 2 You Have Won***");
                }
                else if(buttonUsed[0]==1 && buttonUsed[1]==1 && buttonUsed[2]==1 && buttonUsed[3]==1 && buttonUsed[4]==1 && buttonUsed[5]==1 && buttonUsed[6]==1 && buttonUsed[7]==1 && buttonUsed[8]==1 && result1==0 && result2==0)
                {
                    JOptionPane.showMessageDialog(rootPane,"***Match Drawn !***");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button Has Already Been Used !");
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
        
        turn = 2;
        
        for(int i=0;i<9;i++)
        {
            buttonUsed[i]=0;
        }
        for(int i=0;i<9;i++)
        {
            p1won[i]=0;
        }
        for(int i=0;i<9;i++)
        {
            p2won[i]=0;
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
